import { t, useLocale } from './i18n';
import { useState } from 'react';
import { Button, Checkbox, Tag, TextInput } from '@carbon/react';
import { api, consoleApi, controlApi } from './api';
import { ConfirmModal, DataState, GridTable, Notice, TableCell, TableRow } from './components';
import { number, sourceLabels, timestamp } from './format';
import { useAction, usePolling } from './hooks';
import type { Directory, HistoryPreview } from './types';

export function DirectoriesPage({ active }: { active: boolean }) {
  useLocale();
  const state = usePolling<Directory[]>('/api/console', { action: 'directories' }, active, 1000);
  const [path, setPath] = useState('');
  const [preview, setPreview] = useState<HistoryPreview>();
  const [selected, setSelected] = useState<number[]>([]);
  const [remove, setRemove] = useState<Directory>();
  const [removePreview, setRemovePreview] = useState<{ removes_exclusion: boolean; coverage_may_expand: boolean; enabled_ancestors: string[]; affected_descendants: string[]; after: Directory[] }>();
  const action = useAction();
  const add = () => {
    if (!path.startsWith('/') || !path.trim()) { void action.run(() => Promise.reject(new Error('directories.enterAFullDirectoryPathStartingWith'))); return; }
    void action.run(() => controlApi('add_directories', { entries: [{ path, sources: ['manual'] }] }), 'directories.directoryAddedToMonitoringSettings').then(result => { if (result) { setPath(''); state.refresh(); } });
  };
  const toggle = (directory: Directory) => void action.run(() => consoleApi('directory_set', { path: directory.path, enabled: !directory.enabled }), directory.enabled ? 'directories.directoryDisabledItsEntireSubtreeIsExcluded' : 'directories.directoryEnabled').then(() => state.refresh());
  const removeDirectory = () => void action.run(() => controlApi('remove_directory', { path: remove?.path }), 'directories.monitoringEntryRemovedProjectFilesAndHistory').then(result => { if (result) { setRemove(undefined); state.refresh(); } });
  return <div className="form-stack">
    <section className="panel"><h2>{t('directories.addAMonitoredDirectory')}</h2><form className="directory-add" onSubmit={event => { event.preventDefault(); add(); }}><TextInput id="manual-directory" size="md" labelText={t('directories.fullDirectoryPath')} value={path} onChange={event => setPath(event.target.value)} placeholder="/workspace/project-a" /><div className="actions"><Button kind="tertiary" size="md" disabled={action.busy} onClick={() => void action.run(() => api<{ path: string | null; cancelled: boolean }>('/api/directory/pick', {})).then(result => { if (result?.path) setPath(result.path); })}>{t('directories.chooseDirectory')}</Button><Button type="submit" size="md" disabled={action.busy || !path}>{t('directories.add')}</Button></div></form><p className="helper">{t('directories.thisChangesMonitoringScopeNotProjectFiles')}</p></section>
    <Notice error={action.error} success={action.success} />
    <section className="panel"><div className="section-heading"><h2>{t('directories.currentDirectories')}</h2><span className="helper">{state.data ? t('directories.configurationCount', { count: state.data.length, amount: number(state.data.length) }) : t('directories.unknown')}</span></div>
      <DataState loading={state.loading} error={state.error} empty={!state.data?.length} emptyTitle={t('directories.noDirectoriesConfigured')} emptyText={t('directories.addADirectoryManuallyOrSelectA')}>
        <GridTable label={t('directories.monitoredDirectorySettings')} headings={[t('directories.directory'), t('directories.sources'), t('directories.effectiveCoverage'), t('directories.added'), t('directories.actions')]}>
          {state.data?.map(directory => <TableRow key={directory.path}><TableCell className="path">{directory.path}{!directory.exists && <Tag type="warm-gray">{t('directories.pathDoesNotExist')}</Tag>}</TableCell><TableCell>{directory.sources.map(source => sourceLabels[source] ?? source).join(t('common.listSeparator'))}</TableCell><TableCell>{!directory.enabled ? <strong>{t('directories.disabledSubtreeExcluded')}</strong> : directory.effective ? t('directories.enabled') : t('directories.excluded')}{directory.excluded_by && <p className="helper path">{t('directories.excludedBy', { path: directory.excluded_by })}</p>}</TableCell><TableCell>{timestamp(directory.added_at_ms)}</TableCell><TableCell><div className="actions"><Button kind="ghost" size="sm" disabled={action.busy} onClick={() => toggle(directory)}>{directory.enabled ? t('directories.disable') : t('directories.enabled')}</Button><Button kind="danger--ghost" size="sm" disabled={action.busy} onClick={() => void action.run(() => consoleApi<NonNullable<typeof removePreview>>('directory_remove_preview', { path: directory.path })).then(result => { if (result) { setRemovePreview(result); setRemove(directory); } })}>{t('directories.remove')}</Button></div></TableCell></TableRow>)}
        </GridTable>
      </DataState>
    </section>
    <section className="panel"><div className="section-heading"><div><h2>{t('directories.discoverDirectoriesFromSessionHistory')}</h2><p>{t('directories.importSelectedDirectoryMetadataFromCodexClaude')}</p></div><Button kind="tertiary" size="sm" disabled={action.busy} onClick={() => void action.run(() => api<HistoryPreview>('/api/history/preview', {})).then(result => { if (result) { setPreview(result); setSelected([]); } })}>{action.busy ? t('directories.loading') : t('directories.previewCandidates')}</Button></div>
      {preview && <><div className="preview-summary"><span>{t('directories.candidateCount', { amount: number(preview.candidates.length) })}</span><span>{t('directories.gapCount', { amount: number(preview.gaps.reduce((sum, gap) => sum + gap.count, 0)) })}</span><Button kind="ghost" size="sm" onClick={() => setSelected(preview.candidates.flatMap((candidate, index) => candidate.status === 'available' ? [index] : []))}>{t('directories.selectAvailableCandidates')}</Button><Button kind="ghost" size="sm" onClick={() => setSelected([])}>{t('directories.clearSelection')}</Button></div>
        <GridTable label={t('directories.projectDirectoryCandidatesFromHistory')} headings={[t('directories.select'), t('directories.directory'), t('directories.status'), t('directories.sources')]}>
          {preview.candidates.map((candidate, index) => <TableRow key={index}><TableCell><Checkbox id={`candidate-${index}`} labelText={t('directories.selectCandidate', { candidate: number(index + 1) })} hideLabel checked={selected.includes(index)} disabled={candidate.status !== 'available'} onChange={(_, { checked }) => setSelected(current => checked ? [...current, index] : current.filter(value => value !== index))} /></TableCell><TableCell className="path">{candidate.canonical_path ?? candidate.raw_paths.join(t('common.listSeparator'))}</TableCell><TableCell>{candidateStatus(candidate.status)}</TableCell><TableCell>{Array.from(new Set(candidate.origins.map(origin => sourceLabels[origin.source] ?? origin.source))).join(t('common.listSeparator'))}</TableCell></TableRow>)}
        </GridTable>
        <div className="actions"><Button size="md" disabled={!selected.length || action.busy} onClick={() => void action.run(() => api('/api/history/import', { preview_id: preview.preview_id, indices: selected }), 'directories.selectedAvailableDirectoriesImported').then(result => { if (result) { setSelected([]); state.refresh(); } })}>{t('directories.importSelected', { amount: number(selected.length) })}</Button></div>
        {preview.gaps.length > 0 && <details><summary>{t('directories.discoveryCoverageGaps')}</summary><ul className="path-list">{preview.gaps.map((gap, index) => <li key={index}>{t('directories.sourceGap', { source: sourceLabels[gap.source] ?? gap.source, reason: gapLabel(gap.kind), amount: number(gap.count) })}</li>)}</ul></details>}
        {preview.versions.length > 0 && <details><summary>{t('directories.observedSourceVersions')}</summary><ul className="path-list">{preview.versions.map((version, index) => <li key={index}>{t('directories.sourceVersion', { source: sourceLabels[version.source] ?? version.source, version: version.version, state: version.compatibility_validated ? t('directories.formatVerified') : t('directories.formatCompatibilityUnverified') })}</li>)}</ul></details>}
      </>}
    </section>
    <ConfirmModal open={Boolean(remove)} heading={t('directories.removeMonitoringEntry')} busy={action.busy} error={action.error} close={() => setRemove(undefined)} submit={removeDirectory} text={<><p className="path">{remove?.path}</p><p>{t('directories.onlyThisMonitoringEntryIsRemovedProject')}</p><p>{removePreview?.coverage_may_expand ? t('directories.removingAnExclusionMayRestoreCoverageBy') : t('directories.effectiveScopeIsRecalculatedUsingTheRemaining')}</p><p>{t('directories.overlappingParents', { paths: removePreview?.enabled_ancestors.join(t('common.listSeparator')) || t('directories.none') })}</p>{removePreview?.affected_descendants.length ? <><p>{t('directories.affectedSubdirectoryEntries')}</p><ul className="path-list">{removePreview.affected_descendants.map(path => <li className="path" key={path}>{path}</li>)}</ul></> : null}</>} />
  </div>;
}

function candidateStatus(status: string): string { return ({ available: t('directories.available'), missing: t('directories.pathDoesNotExist'), unresolved: t('directories.unresolved'), inaccessible: t('directories.inaccessible'), not_directory: t('directories.notADirectory') } as Record<string, string>)[status] ?? status; }
function gapLabel(kind: string): string { return ({ missing_source: t('directories.sourceMissing'), io_error: t('directories.cannotRead'), malformed_record: t('directories.invalidRecordFormat'), incomplete_record: t('directories.incompleteDirectoryMetadata'), record_too_long: t('directories.oversizedRecordSkipped'), unsupported_format: t('directories.unsupportedFormat'), missing_directory: t('directories.projectDirectoryMissing'), missing_version: t('directories.versionMissing'), version_not_validated: t('directories.versionCompatibilityUnverified'), directory_changes_not_validated: t('directories.directoryChangeFormatUnverified'), read_timed_out: t('directories.readTimedOut'), skipped_symlink: t('directories.symbolicLinkSkipped') } as Record<string, string>)[kind] ?? kind; }
